import type { MedicationPhase } from "./types";

const unvalidatedInterval = (targetMinutes: number | null) => ({
  targetMinutes,
  minimumMinutes: null,
  maximumMinutes: null,
  source: null,
  confirmedAt: null,
  confirmedBy: null,
  notes: "Tolerâncias aguardando validação profissional.",
});

const CONFIRMED_WITH_PRESCRIBER = "Confirmado com o médico prescritor em 07/08/2026";
const CONFIRMED_BY_PATIENT = "Confirmado por Lucas em 07/08/2026";

const metronidazolInterval = {
  targetMinutes: 480,
  minimumMinutes: 420,
  maximumMinutes: 540,
  source: CONFIRMED_WITH_PRESCRIBER,
  confirmedAt: "2026-08-07T00:00:00Z",
  confirmedBy: "Lucas",
  notes: "Tolerância de até 1h para mais ou menos em torno do intervalo-alvo de 8h.",
};

const metronidazolReschedule = {
  moveFutureDoses: true,
  confirmed: true,
  source: CONFIRMED_WITH_PRESCRIBER,
  confirmedAt: "2026-08-07T00:00:00Z",
  confirmedBy: "Lucas",
} as const;

const patientConfirmedReschedule = {
  moveFutureDoses: true,
  confirmed: true,
  source: CONFIRMED_BY_PATIENT,
  confirmedAt: "2026-08-07T00:00:00Z",
  confirmedBy: "Lucas",
} as const;

export const INITIAL_TREATMENT_PHASES: MedicationPhase[] = [
  {
    id: "nexium-continuo",
    medicationId: "nexium",
    medicationName: "Nexium / esomeprazol 40 mg",
    phaseName: "Uso contínuo",
    startDate: "2026-08-06",
    endDate: null,
    continuous: true,
    doseQuantity: 1,
    doseUnit: "comprimido",
    dosesPerDay: 1,
    interval: unvalidatedInterval(null),
    rigidity: "high",
    slotStrategy: "wake",
    reschedulePolicy: patientConfirmedReschedule,
  },
  {
    id: "nac-fase-unica",
    medicationId: "nac",
    medicationName: "NAC 600 mg",
    phaseName: "06/08 a 19/08",
    startDate: "2026-08-06",
    endDate: "2026-08-19",
    doseQuantity: 1,
    doseUnit: "unidade",
    dosesPerDay: 2,
    interval: unvalidatedInterval(null),
    rigidity: "high",
    slotStrategy: "wake",
    reschedulePolicy: patientConfirmedReschedule,
    morningGroupingWithNexium: {
      confirmed: true,
      source: CONFIRMED_BY_PATIENT,
    },
  },
  {
    id: "rifaximina-fase-unica",
    medicationId: "rifaximina",
    medicationName: "Rifaximina 550 mg",
    phaseName: "06/08 a 19/08",
    startDate: "2026-08-06",
    endDate: "2026-08-19",
    doseQuantity: 1,
    doseUnit: "comprimido",
    dosesPerDay: 2,
    interval: unvalidatedInterval(720),
    rigidity: "high",
    slotStrategy: "after_morning_nac",
    dependency: {
      medicationId: "nac",
      minimumMinutes: 30,
      maximumMinutes: 60,
      confirmed: true,
      source: "PRD v1.0 — prescrição informada",
    },
    reschedulePolicy: patientConfirmedReschedule,
  },
  {
    id: "metronidazol-fase-unica",
    medicationId: "metronidazol",
    medicationName: "Metronidazol 250 mg",
    phaseName: "06/08 a 19/08",
    startDate: "2026-08-06",
    endDate: "2026-08-19",
    doseQuantity: 1,
    doseUnit: "comprimido",
    dosesPerDay: 3,
    interval: metronidazolInterval,
    rigidity: "high",
    slotStrategy: "target_interval",
    reschedulePolicy: metronidazolReschedule,
  },
  {
    id: "berberina-fase-1",
    medicationId: "berberina-caprilico",
    medicationName: "Berberina + Caprílico",
    phaseName: "Fase 1",
    startDate: "2026-08-06",
    endDate: "2026-08-20",
    doseQuantity: 2,
    doseUnit: "cápsulas",
    dosesPerDay: 2,
    interval: unvalidatedInterval(null),
    rigidity: "high",
    slotStrategy: "meal_blocks",
    reschedulePolicy: patientConfirmedReschedule,
  },
  {
    id: "berberina-fase-2",
    medicationId: "berberina-caprilico",
    medicationName: "Berberina + Caprílico",
    phaseName: "Fase 2",
    startDate: "2026-08-21",
    endDate: "2026-10-04",
    doseQuantity: 2,
    doseUnit: "cápsulas",
    dosesPerDay: 1,
    interval: unvalidatedInterval(null),
    rigidity: "high",
    slotStrategy: "meal_blocks",
    reschedulePolicy: patientConfirmedReschedule,
  },
  {
    id: "oregano-fase-unica",
    medicationId: "oleo-oregano",
    medicationName: "Óleo de orégano 250 mg",
    phaseName: "06/08 a 04/09",
    startDate: "2026-08-06",
    endDate: "2026-09-04",
    doseQuantity: 1,
    doseUnit: "cápsula",
    dosesPerDay: 1,
    interval: unvalidatedInterval(null),
    rigidity: "high",
    slotStrategy: "before_dinner",
    reschedulePolicy: patientConfirmedReschedule,
  },
];
